import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/app/components/navbar/nav';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col w-full h-full relative'>
          <Nav />
          <div id='main-wrapper' className='flex-1 relative overflow-y-scroll lg:px-5'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
